### ISSUE TITLE
MAS patch. Disabled private _NS<...>KillRing functions

### ISSUE THREAD

**Issue by ghost** [iridium-browser/iridium-browser-osx#1]
In order to pass review for Mac App Store (MAS) we have disabled _NS<...>KillRing functions. After some testing I still couldn't see any visible effect of this change but for the sake of reference and documentation we add this issue.

**Comment by ghost** [comment]
Issue in Chromium tracker https://code.google.com/p/chromium/issues/detail?id=496049

**Comment by Ivansss** [comment]
Removed MAS build support since version 46.0.
