### ISSUE TITLE
MAS patch. Disabled private _NSDrawCarbonThemeBezel and _NSDrawCarbonThemeListBox functions

### ISSUE THREAD

**Issue by ghost** [iridium-browser/iridium-browser-osx#2]
_NSDrawCarbonThemeBezel and _NSDrawCarbonThemeListBox are disabled in order to pass Mac App Store (MAS) review.
The side effect of this is inability to draw bordered text boxes in some cases.

![screen shot 2015-05-19 at 12 08 40](https://cloud.githubusercontent.com/assets/6408468/7940893/fdebdf3e-0953-11e5-85a2-f2fe21672850.png)

**Comment by ghost** [comment]
Issue in Chromium tracker https://code.google.com/p/chromium/issues/detail?id=496049

**Comment by Ivansss** [comment]
Removed MAS build support since version 46.0.
