### ISSUE TITLE
Having trouble opening Chrome apps

### ISSUE THREAD

**Issue by corysimmons** [iridium-browser/iridium-browser-osx#20]
For instance: Signal, Simple EPUB Reader, etc.

Anytime I try to open them I get one of these:

![image](https://cloud.githubusercontent.com/assets/224636/16811128/f4a94eb6-48f4-11e6-8e6b-4b5a28a514f3.png)

I'm able to ignore the warning and click around on the app, but they aren't particularly functional. For instance, I can go through the entire setup with Signal, but when I go to use it again it throws that error and effectively resets the app.

Is this a known issue?

**Comment by medozas** [comment]
@ryanzarafa : you have an idea on this. I couldn't reproduce this so far.

**Comment by medozas** [comment]
fixed
