### ISSUE TITLE
provide current version over brew

### ISSUE THREAD

**Issue by mtz** [iridium-browser/iridium-browser-osx#25]
Hi,

there is no download or upgrade of current version (not latest) via brew upgrade nor brew cu possible. There is still v61.0.0 available.

I don't know if you have to update the versions. If yes, please update.

Thanks
mtz

**Comment by tinfoil920-39io** [comment]
The good news for those who suffer using **windows** without being financially compensated by an employer is chocolatey is up to date

https://chocolatey.org/packages/iridium-browser

😿  🎉

**Comment by medozas** [comment]
@tinfoil920-39io thanks!
