### ISSUE TITLE
Iridium Framework.framework has duplicate content

### ISSUE THREAD

**Issue by avioli** [iridium-browser/iridium-browser-osx#26]
600Mb is crazy!

I opened the bundle and drilled inside until I found that `Current` is a copy of `A`.

Located at `/Contents/Versions/2017.11.0.0/Iridium Framework.framework/Versions/` and it should be a symlink. Diff-ed and they are identical.

200Mb wasted.

**Comment by avioli** [comment]
Oh and `Iridium Framework` binary is about 138mb... doubled as well. Tripled, given the above.

```shell
> cd Iridium.app/Contents/Versions/2017.11.0.0/Iridium\ Framework.framework/Versions/A/
> shasum -a 256 Iridium\ Framework
5d3447b106b51a67a15947d703187d4a72c2abdbcca3fdaf9375ae5a036b6497  Iridium Framework
> shasum -a 256 ../../Iridium\ Framework
5d3447b106b51a67a15947d703187d4a72c2abdbcca3fdaf9375ae5a036b6497  ../../Iridium Framework
```

**Comment by avioli** [comment]
`Resources` inside the `Iridium Framework.framework` and in the sub-directory `Versions/A/` are _almost_ identical - only `app_mode_loader.app` differs.

Another 54-ish Mb.

Can't these be consolidated somehow?

It will slim down the bundle with a whooping 392Mb!!!

**Comment by medozas** [comment]
thanks for reporting - the current build now only has 68M - marking as fixed.
