### ISSUE TITLE
MAS patch. Disabled private vproc_swap_complex function

### ISSUE THREAD

**Issue by ghost** [iridium-browser/iridium-browser-osx#3]
Disabled vproc_swap_complex private function to pass Mac App Store review. The result of this inability to get launchd parameters which disables work of service management (now the only thing which use it is Cloud printing).

**Comment by ghost** [comment]
Issue in Chromium tracker https://code.google.com/p/chromium/issues/detail?id=496049

**Comment by Ivansss** [comment]
Removed MAS build support since version 46.0.
