### ISSUE TITLE
MAS patch. Disabled private methods to get Dock preferences

### ISSUE THREAD

**Issue by ghost** [iridium-browser/iridium-browser-osx#4]
Disabled private method CFURLCreateFromPropertyListRepresentation to get some of the Dock preferences in order to pass Mac App Store review. After testing we couldn't find any visible regression.

**Comment by ghost** [comment]
Issue in Chromium tracker https://code.google.com/p/chromium/issues/detail?id=496049

**Comment by Ivansss** [comment]
Removed MAS build support since version 46.0.
