### ISSUE TITLE
MAS patch. Disabled private API to check and block bundle executable loading

### ISSUE THREAD

**Issue by ghost** [iridium-browser/iridium-browser-osx#5]
Disabled private function _CFBundleLoadExecutableAndReturnError in order to pass Mac App Store review. This disables some google checks on bundle executable. This change should not cause any regression.

**Comment by ghost** [comment]
Issue in Chromium tracker https://code.google.com/p/chromium/issues/detail?id=496049

**Comment by Ivansss** [comment]
Removed MAS build support since version 46.0.
