### ISSUE TITLE
MAS patch. Disabled private CGSSetDenyWindowServerConnections and CGSShutdownServerConnections functions

### ISSUE THREAD

**Issue by ghost** [iridium-browser/iridium-browser-osx#6]
Disabled private functions CGSSetDenyWindowServerConnections and CGSShutdownServerConnections in the code. There were no visible consequences for this change but it might be that we are no leaving dangling connections to window server in sandbox warmup. This of course is only true in case sandbox warmup does something for MAS version of the application since MAS version should be sandbox right after start and limit information collection in void Sandbox::SandboxWarmup function in content/common/sandbox_mac.mm file.

**Comment by ghost** [comment]
Issue in Chromium tracker https://code.google.com/p/chromium/issues/detail?id=496049

**Comment by Ivansss** [comment]
Removed MAS build support since version 46.0.
