### ISSUE TITLE
Build with support for proprietary codecs

### ISSUE THREAD

**Issue by fancycode** [iridium-browser/iridium-browser-osx#8]
The `GYP_DEFINES` should contain `proprietary_codecs=1` when running `gclient sync` / `gclient runhooks` to enable support for additional mime types.

**Comment by fancycode** [comment]
You can check iridium-browser/iridium-browser-windows@6e7035d1937871f7f206d3bc7c58cda3fd926da2 for the Windows version.

**Comment by Ivansss** [comment]
Support for proprietary codecs was added in Iridium version 43.8.1.
