### ISSUE TITLE
Build second installer containing proprietary codecs

### ISSUE THREAD

**Issue by fancycode** [iridium-browser/iridium-browser-osx#9]
The OSX version should also be provided as a `-extra` installer containing a version of ffmpegsumo compiled with `ffmpeg_branding=Chrome` in the `GYP_DEFINES`.

You can check iridium-browser/iridium-browser-windows@d64a29854c8db16beff0f771815a6ab0fe748e2b and iridium-browser/iridium-browser-windows@51fe5bef0de984fa10452bb5615ce8e1ba3888a7 to see how this is done for the Windows version.

**Comment by Ivansss** [comment]
Build scripts were changed to build an Iridium extra version in Iridium version 43.8.1.
